# Generated by Django 4.1.3 on 2022-11-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField()),
                (
                    "title_orig",
                    models.CharField(max_length=255, verbose_name="Original title"),
                ),
                (
                    "image_url",
                    models.CharField(max_length=255, verbose_name="Image URL"),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=255, verbose_name="Translated title"),
                ),
                ("pub_date", models.DateTimeField(verbose_name="Published date")),
            ],
        ),
    ]
