# Generated by Django 4.1.3 on 2022-11-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="sent_at",
            field=models.DateTimeField(default=None),
        ),
    ]
