# Generated by Django 4.1.3 on 2022-11-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air", "0003_alter_show_description_alter_show_image_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="source_url",
            field=models.CharField(
                default=None, max_length=255, verbose_name="URL of the show"
            ),
        ),
    ]
